#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap          15
bspc config border_width        3
bspc border_radius              4 

bspc config focused_border_color    \#ad8ee6
bspc config normal_border_color     \#040507

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Spotify state=floating

~/.config/polybar/./launch.sh
feh --bg-scale ~/Imágenes/Wallpaper.png
picom --experimental-backends &
